name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      docker:
        image: localstack/localstack
        options: --privileged
        ports:
          - 4566:4566
          - 4571:4571

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.5

    - name: Wait for Localstack to be ready
      run: |
        until curl -s http://localhost:4566/health | grep "\"s3\": \"running\""; do
          echo "Waiting for Localstack..."
          sleep 5
        done

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
