name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

    - name: Pull Localstack Docker image
      run: |
        docker pull localstack/localstack

    - name: Start Localstack
      run: |
        docker run -d --name localstack -e SERVICES=s3 -p 4566:4566 localstack/localstack

    - name: Wait for Localstack
      run: |
        echo "Waiting for Localstack to be ready..."
        until curl -s http://localhost:4566/health | grep "\"s3\": \"running\""; do
          echo "Waiting for Localstack..."
          sleep 5
        done
        echo "Localstack is ready!"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
